const QUESTIONS=window.MMPI_QUESTIONS,KEYS=window.MMPI_KEYS,NORMS=window.MMPI_NORMS;
const ORDER=['L','F','K','Hs','D','Hy','Pd','Mf','Pa','Pt','Sc','Ma','Si'];
const STORE='mmpi-mobile-v3';
const $=id=>document.getElementById(id);
const fresh=()=>({norm:'male',answers:Array(566).fill(null),current:0,started:false});
let storageOK=true,state=load(),selectedNorm=state.norm||'male';
function load(){try{const x=JSON.parse(localStorage.getItem(STORE));if(x&&Array.isArray(x.answers)&&x.answers.length===566){x.answers=x.answers.map(v=>['D','Y','B'].includes(v)?v:null);x.current=Math.max(0,Math.min(565,+x.current||0));x.norm=x.norm==='female'?'female':'male';return {...fresh(),...x}}}catch(e){storageOK=false}return fresh()}
function save(){try{localStorage.setItem(STORE,JSON.stringify(state));storageOK=true}catch(e){storageOK=false}}
function only(id){['intro','test','results'].forEach(x=>$(x).classList.toggle('hidden',x!==id));$('topbar').classList.toggle('hidden',id!=='test');$('actions').classList.toggle('hidden',id!=='test');scrollTo(0,0)}
function normButtons(){$('maleBtn').classList.toggle('selected',selectedNorm==='male');$('femaleBtn').classList.toggle('selected',selectedNorm==='female')}
function intro(){normButtons();const has=state.started||state.answers.some(Boolean);$('resumeBtn').classList.toggle('hidden',!has);$('resetIntroBtn').classList.toggle('hidden',!has);$('startBtn').textContent=has?'Baştan yeni test başlat':'Teste başla';$('storageWarning').classList.toggle('hidden',storageOK);only('intro')}
function start(){if(state.answers.some(Boolean)&&!confirm('Kayıtlı cevaplar silinip yeni test başlatılsın mı?'))return;state=fresh();state.norm=selectedNorm;state.started=true;save();openTest(0)}
function resume(){state.norm=selectedNorm;state.started=true;let i=state.answers.findIndex(v=>v===null);openTest(i<0?565:i)}
function openTest(i){state.current=Math.max(0,Math.min(565,i));state.started=true;save();only('test');render()}
function render(){const i=state.current,a=state.answers[i];$('qno').textContent='Soru '+(i+1);$('qtext').textContent=QUESTIONS[i]||'Soru yüklenemedi';$('currentAnswer').innerHTML=a?'Seçimin: <b>'+(a==='D'?'Doğru':a==='Y'?'Yanlış':'Boş')+'</b>':'Henüz cevaplanmadı';const done=state.answers.filter(v=>v!==null).length;$('counter').textContent=(i+1)+' / 566 · '+done+' tamam';$('progressBar').style.width=(done/566*100)+'%';$('prevBtn').disabled=i===0}
function answer(v){state.answers[state.current]=v;save();if(navigator.vibrate)navigator.vibrate(10);state.current<565?openTest(state.current+1):results()}
function grid(){const g=$('qgrid');g.textContent='';state.answers.forEach((a,i)=>{const b=document.createElement('button');b.textContent=i+1;b.className=(a||'')+(i===state.current?' active':'');b.onclick=()=>{$('gridModal').classList.add('hidden');openTest(i)};g.appendChild(b)});$('gridModal').classList.remove('hidden')}
function score(k){let n=0;for(const q of k.D)if(state.answers[q-1]==='D')n++;for(const q of k.Y)if(state.answers[q-1]==='Y')n++;return n}
function calc(){const r={L:score(KEYS.L),F:score(KEYS.F),K:score(KEYS.K),Hs:score(KEYS.Hs),D:score(KEYS.D),Hy:score(KEYS.Hy),Pd:score(KEYS.Pd),Mf:score(state.norm==='female'?KEYS.Mf_f:KEYS.Mf_m),Pa:score(KEYS.Pa),Pt:score(KEYS.Pt),Sc:score(KEYS.Sc),Ma:score(KEYS.Ma),Si:score(KEYS.Si)};const c={...r};c.Hs=r.Hs+Math.floor(r.K*.5+.5);c.Pd=r.Pd+Math.floor(r.K*.4+.5);c.Pt=r.Pt+r.K;c.Sc=r.Sc+r.K;c.Ma=r.Ma+Math.floor(r.K*.2+.5);const t={};for(const s of ORDER){const [m,sd]=NORMS[state.norm][s];t[s]=50+10*(c[s]-m)/sd}return{r,c,t}}
function results(){only('results');const done=state.answers.filter(v=>v!==null).length,blank=state.answers.filter(v=>v==='B').length;$('doneCount').textContent=done-blank;$('blankCount').textContent=blank;$('leftCount').textContent=566-done;$('resultMeta').textContent=(state.norm==='female'?'Kadın':'Erkek')+' normu · '+done+'/566 soru geçildi';const s=calc(),body=$('resultBody');body.textContent='';for(const k of ORDER){const tr=document.createElement('tr'),changed=['Hs','Pd','Pt','Sc','Ma'].includes(k);tr.innerHTML='<td>'+k+'</td><td>'+s.r[k]+'</td><td>'+(changed?s.c[k]:'-')+'</td><td class="'+(s.t[k]>=65?'t-high':'')+'">'+s.t[k].toFixed(1)+'</td>';body.appendChild(tr)}requestAnimationFrame(()=>chart(s.t))}
function chart(t){const cv=$('profileChart'),r=cv.getBoundingClientRect(),d=Math.max(1,devicePixelRatio||1);cv.width=Math.round(r.width*d);cv.height=Math.round(r.height*d);const x=cv.getContext('2d');x.scale(d,d);const w=r.width,h=r.height,p={l:38,r:14,t:18,b:42},pw=w-p.l-p.r,ph=h-p.t-p.b,Y=v=>p.t+(100-v)/80*ph,X=i=>p.l+i*pw/(ORDER.length-1);x.clearRect(0,0,w,h);x.font='11px -apple-system,sans-serif';for(let v=20;v<=100;v+=10){x.strokeStyle=v===50?'#79634f':'#3d332a';x.beginPath();x.moveTo(p.l,Y(v));x.lineTo(w-p.r,Y(v));x.stroke();x.fillStyle='#a99a8a';x.textAlign='right';x.textBaseline='middle';x.fillText(v,p.l-7,Y(v))}x.strokeStyle='#d5aa6d';x.lineWidth=2.5;x.beginPath();ORDER.forEach((s,i)=>{const y=Y(Math.max(20,Math.min(100,t[s])));i?x.lineTo(X(i),y):x.moveTo(X(i),y)});x.stroke();ORDER.forEach((s,i)=>{const y=Y(Math.max(20,Math.min(100,t[s])));x.fillStyle='#15120f';x.strokeStyle='#d5aa6d';x.beginPath();x.arc(X(i),y,4,0,Math.PI*2);x.fill();x.stroke();x.fillStyle='#c9baa9';x.textAlign='center';x.textBaseline='top';x.fillText(s,X(i),h-p.b+10)})}
function backup(){const blob=new Blob([JSON.stringify({state,scores:calc()},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='mmpi-cevaplari.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
function restore(file){const rd=new FileReader();rd.onload=()=>{try{const o=JSON.parse(rd.result),x=o.state||o;if(!Array.isArray(x.answers)||x.answers.length!==566)throw 0;state={...fresh(),...x};selectedNorm=state.norm==='female'?'female':'male';save();results()}catch(e){alert('Yedek dosyası okunamadı')}};rd.readAsText(file)}
function reset(){if(confirm('Bütün cevaplar silinsin mi?')){try{localStorage.removeItem(STORE)}catch(e){}state=fresh();selectedNorm='male';intro()}}
$('maleBtn').onclick=()=>{selectedNorm='male';normButtons()};$('femaleBtn').onclick=()=>{selectedNorm='female';normButtons()};$('startBtn').onclick=start;$('resumeBtn').onclick=resume;$('resetIntroBtn').onclick=reset;document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(b.dataset.answer));$('prevBtn').onclick=()=>openTest(state.current-1);$('gridBtn').onclick=grid;$('resultBtn').onclick=results;$('closeGridBtn').onclick=()=>$('gridModal').classList.add('hidden');$('gridModal').onclick=e=>{if(e.target===$('gridModal'))$('gridModal').classList.add('hidden')};$('backToTestBtn').onclick=()=>openTest(state.current);$('exportBtn').onclick=backup;$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=e=>{if(e.target.files[0])restore(e.target.files[0]);e.target.value=''};$('resetBtn').onclick=reset;$('printBtn').onclick=()=>print();addEventListener('resize',()=>{if(!$('results').classList.contains('hidden'))chart(calc().t)});
try{if(QUESTIONS.length!==566)throw Error('Sorular eksik: '+QUESTIONS.length);intro()}catch(e){document.body.insertAdjacentHTML('afterbegin','<div style="position:fixed;z-index:9999;inset:12px 12px auto;padding:12px;border-radius:12px;background:#7a2f2b;color:white">Uygulama başlatılamadı: '+e.message+'</div>')}
